apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snake-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snake-scheduler
subjects:
  - kind: ServiceAccount
    name: snake-scheduler
    namespace: snake-scheduler
