---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-scheduler
  labels:
    app.kubernetes.io/name: snake-scheduler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: snake-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snake-scheduler
    spec:
      serviceAccountName: snake-scheduler
      containers:
        - args:
            - --enable-leader-election
          image: dpush/snake-scheduler:latest
          name: snake-scheduler
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 20Mi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      terminationGracePeriodSeconds: 10
