dist: xenial
os: linux
language: java

before_install:
  # Install Bazel
  # TODO: this should be using Bazelisk or Docker or something...
  - OS=linux
  - ARCH=x86_64
  - V=2.2.0
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS=darwin; fi
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
  - GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

install:
  - hack/tools/install.sh

script:
  # dont use just recipes for build/test to avoid running gazelle in CI
  - bazel build --config=ci //...
  - bazel test --config=ci //...
  - bin/just check
